=== viktorgino/navit/navit/navit.dtd
<!ELEMENT config (plugins,debug*,navit)>
<!ATTLIST config xmlns:xi CDATA #REQUIRED>
<!ATTLIST config language CDATA #IMPLIED>
<!ELEMENT plugins (plugin*)>
<!ELEMENT plugin EMPTY>
<!ATTLIST plugin path CDATA #REQUIRED>
<!ATTLIST plugin active CDATA #IMPLIED>
<!ATTLIST plugin ondemand CDATA #IMPLIED>
<!ELEMENT debug EMPTY>
<!ATTLIST debug name CDATA #REQUIRED>
<!ATTLIST debug level CDATA "0">
<!ATTLIST debug dbg_level (error|warning|info|debug) "error">
<!ELEMENT log EMPTY>
<!ATTLIST log enabled CDATA #IMPLIED>
<!ATTLIST log type CDATA #REQUIRED>
<!ATTLIST log data CDATA #REQUIRED>
<!ATTLIST log flush_size CDATA #IMPLIED>
<!ATTLIST log flush_time CDATA #IMPLIED>
<!ATTLIST log attr_types CDATA #IMPLIED>
<!ELEMENT navit (graphics,gui+,log*,osd*,traffic*,vehicle*,tracking?,vehicleprofile*,route,navigation,speech,mapset+,layer+,xi:include+,layout+) >
<!ATTLIST navit center CDATA #REQUIRED>
<!ATTLIST navit zoom CDATA #REQUIRED>
<!ATTLIST navit tracking CDATA #REQUIRED>
<!ATTLIST navit orientation CDATA #REQUIRED>
<!ATTLIST navit recent_dest CDATA #IMPLIED>
<!ATTLIST navit drag_bitmap CDATA #IMPLIED>
<!ATTLIST navit default_layout CDATA #IMPLIED>
<!ATTLIST navit tunnel_nightlayout CDATA #IMPLIED>
<!ATTLIST navit nightlayout_auto CDATA #IMPLIED>
<!ATTLIST navit sunrise_degrees CDATA #IMPLIED>
<!ELEMENT gui ANY>
<!ATTLIST gui type CDATA #REQUIRED>
<!ATTLIST gui menubar CDATA #IMPLIED>
<!ATTLIST gui toolbar CDATA #IMPLIED>
<!ATTLIST gui statusbar CDATA #IMPLIED>
<!ATTLIST gui skin CDATA #IMPLIED>
<!ATTLIST gui fullscreen CDATA #IMPLIED>
<!ATTLIST gui enabled CDATA #IMPLIED>
<!ELEMENT graphics EMPTY>
<!ATTLIST graphics type CDATA #REQUIRED>
<!ATTLIST graphics event_loop_system CDATA #IMPLIED>
<!ELEMENT vehicle (log*)>
<!ATTLIST vehicle name CDATA #REQUIRED>
<!ATTLIST vehicle source CDATA #REQUIRED>
<!ATTLIST vehicle enabled CDATA #IMPLIED>
<!ATTLIST vehicle active CDATA #IMPLIED>
<!ATTLIST vehicle follow CDATA #IMPLIED>
<!ATTLIST vehicle update CDATA #IMPLIED>
<!ATTLIST vehicle gpsd_query CDATA #IMPLIED>
<!ATTLIST vehicle profilename CDATA #IMPLIED>
<!ELEMENT vehicleprofile (roadprofile+)>
<!ATTLIST vehicleprofile name CDATA #REQUIRED>
<!ATTLIST vehicleprofile flags CDATA #REQUIRED>
<!ATTLIST vehicleprofile flags_forward_mask CDATA #REQUIRED>
<!ATTLIST vehicleprofile flags_reverse_mask CDATA #REQUIRED>
<!ATTLIST vehicleprofile maxspeed_handling CDATA #REQUIRED>
<!ATTLIST vehicleprofile route_mode CDATA #REQUIRED>
<!ATTLIST vehicleprofile route_depth CDATA #IMPLIED>
<!ATTLIST vehicleprofile static_distance CDATA #IMPLIED>
<!ATTLIST vehicleprofile static_speed CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_width CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_height CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_length CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_weight CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_axle_weight CDATA #IMPLIED>
<!ELEMENT coord EMPTY>
<!ATTLIST coord x CDATA #REQUIRED>
<!ATTLIST coord y CDATA #REQUIRED>
<!ELEMENT cursor (itemgra+)>
<!ATTLIST cursor w CDATA #REQUIRED>
<!ATTLIST cursor h CDATA #REQUIRED>
<!ELEMENT traffic EMPTY>
<!ATTLIST traffic type CDATA #REQUIRED>
<!ELEMENT tracking ANY>
<!ATTLIST tracking cdf_histsize CDATA #IMPLIED>
<!ELEMENT route EMPTY>
<!ATTLIST route destination_distance CDATA #IMPLIED>
<!ELEMENT roadprofile (announcement*)>
<!ATTLIST roadprofile item_types CDATA #REQUIRED>
<!ATTLIST roadprofile speed CDATA #REQUIRED>
<!ATTLIST roadprofile route_weight CDATA #REQUIRED>
<!ELEMENT speed EMPTY>
<!ATTLIST speed type CDATA #REQUIRED>
<!ATTLIST speed value CDATA #REQUIRED>
<!ELEMENT navigation (announce+)>
<!ELEMENT announce EMPTY>
<!ATTLIST announce type CDATA #REQUIRED>
<!ATTLIST announce level0 CDATA #IMPLIED>
<!ATTLIST announce level1 CDATA #IMPLIED>
<!ATTLIST announce level2 CDATA #IMPLIED>
<!ATTLIST announce unit CDATA #REQUIRED>
<!ELEMENT announcement EMPTY>
<!ATTLIST announcement level CDATA #REQUIRED>
<!ATTLIST announcement distance_metric CDATA #REQUIRED>
<!ELEMENT speech EMPTY>
<!ATTLIST speech type CDATA #REQUIRED>
<!ATTLIST speech data CDATA #REQUIRED>
<!ATTLIST speech cps CDATA #IMPLIED>
<!ELEMENT mapset (map*,xi:include*)>
<!ATTLIST mapset enabled CDATA #IMPLIED>
<!ELEMENT map EMPTY>
<!ATTLIST map type CDATA #REQUIRED>
<!ATTLIST map enabled CDATA #IMPLIED>
<!ATTLIST map active CDATA #IMPLIED>
<!ATTLIST map data CDATA #REQUIRED>
<!ATTLIST map cursor CDATA #IMPLIED>
<!ELEMENT layout (cursor*,xi:include*,layer+)*>
<!ATTLIST layout name CDATA #REQUIRED>
<!ATTLIST layout active CDATA #IMPLIED>
<!ATTLIST layout color CDATA #IMPLIED>
<!ATTLIST layout font CDATA #IMPLIED>
<!ATTLIST layout daylayout CDATA #IMPLIED>
<!ATTLIST layout nightlayout CDATA #IMPLIED>
<!ATTLIST layout icon_w CDATA #IMPLIED>
<!ATTLIST layout icon_h CDATA #IMPLIED>
<!ATTLIST layout underground_alpha CDATA #IMPLIED>
<!ATTLIST layout xmlns:xi CDATA #IMPLIED>
<!ELEMENT layer (itemgra*)>
<!ATTLIST layer enabled CDATA #IMPLIED>
<!ATTLIST layer name CDATA #IMPLIED>
<!ATTLIST layer details CDATA #IMPLIED>
<!ATTLIST layer order CDATA #IMPLIED>
<!ATTLIST layer ref CDATA #IMPLIED>
<!ATTLIST layer active CDATA #IMPLIED>
<!ELEMENT osd EMPTY>
<!ATTLIST osd enabled CDATA #IMPLIED>
<!ATTLIST osd type CDATA #REQUIRED>
<!ATTLIST osd x CDATA #IMPLIED>
<!ATTLIST osd y CDATA #IMPLIED>
<!ATTLIST osd src CDATA #IMPLIED>
<!ATTLIST osd command CDATA #IMPLIED>
<!ELEMENT itemgra (polygon|polyline|text|circle|icon|image|arrows|spikes)*>
<!ATTLIST itemgra item_types CDATA #IMPLIED>
<!ATTLIST itemgra order CDATA #IMPLIED>
<!ATTLIST itemgra speed_range CDATA #IMPLIED>
<!ELEMENT polygon (coord*)>
<!ATTLIST polygon color CDATA #REQUIRED>
<!ATTLIST polygon oneway CDATA #IMPLIED>
<!ELEMENT polyline (coord*)>
<!ATTLIST polyline color CDATA #REQUIRED>
<!ATTLIST polyline width CDATA #IMPLIED>
<!ATTLIST polyline dash CDATA #IMPLIED>
<!ATTLIST polyline offset CDATA #IMPLIED>
<!ATTLIST polyline radius CDATA #IMPLIED>
<!ATTLIST polyline oneway CDATA #IMPLIED>
<!ELEMENT text EMPTY>
<!ATTLIST text text_size CDATA #REQUIRED>
<!ATTLIST text color CDATA #IMPLIED>
<!ATTLIST text background_color CDATA #IMPLIED>
<!ATTLIST text oneway CDATA #IMPLIED>
<!ELEMENT circle (coord*)>
<!ATTLIST circle color CDATA #REQUIRED>
<!ATTLIST circle radius CDATA #REQUIRED>
<!ATTLIST circle width CDATA #IMPLIED>
<!ATTLIST circle text_size CDATA #IMPLIED>
<!ATTLIST circle background_color CDATA #IMPLIED>
<!ATTLIST circle oneway CDATA #IMPLIED>
<!ELEMENT icon EMPTY>
<!ATTLIST icon src CDATA #REQUIRED>
<!ATTLIST icon w CDATA #IMPLIED>
<!ATTLIST icon h CDATA #IMPLIED>
<!ATTLIST icon x CDATA #IMPLIED>
<!ATTLIST icon y CDATA #IMPLIED>
<!ELEMENT arrows EMPTY>
<!ATTLIST arrows color CDATA #REQUIRED>
<!ATTLIST arrows width CDATA #IMPLIED>
<!ATTLIST arrows oneway CDATA #IMPLIED>
<!ELEMENT spikes EMPTY>
<!ATTLIST spikes color CDATA #REQUIRED>
<!ATTLIST spikes width CDATA #IMPLIED>
<!ATTLIST spikes distance CDATA #IMPLIED>
<!ELEMENT image EMPTY>
<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include href CDATA #IMPLIED>
<!ATTLIST xi:include xpointer CDATA #IMPLIED>

=== viktorgino/navit/navit/navit_shipped.xml
<?xml version="1.0" encoding="UTF-8"?><!--
	For configuration options used in this file, please read
	http://wiki.navit-project.org/index.php/Configuration
	Do not edit /usr/share/navit/navit.xml or /etc/navit/navit.xml :
	changes would be lost on upgrade. Rather copy it to ~/.navit/.
-->
<!DOCTYPE config
  SYSTEM "navit.dtd">
<config xmlns:xi="http://www.w3.org/2001/XInclude">
	<plugins>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}lib*.so" ondemand="yes"/>
		<plugin path="$NAVIT_LIBDIR/autoload/${NAVIT_LIBPREFIX}lib*.so"/>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}libbinding_dbus.so" active="no"/>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}libgraphics_null.so" active="no"/>
	</plugins>

	<!-- The global debug level (like using command line option "-d"). Ignored if option -d is used. -->
	<!-- Possible debug levels: error, warning, info, debug. -->
	<debug name="global" dbg_level="error"/>
	<!-- Example of setting the debug level for a single function.  -->
	<debug name="navit:do_draw" dbg_level="error"/>
	<debug name="navit" dbg_level="warning"/>

	<!-- Example for logging timing/profiling information. Note the prefix "profile:".
	<debug name="profile:navit:do_draw" dbg_level="debug"/>
	-->
	<!-- segv: 1 - show backtrace with gdb and exit, 2 - stay in gdb -->
	<debug name="segv" level="1"/>
	<!-- timestamps 0/1 - prefix log messages with a timestamp -->
	<debug name="timestamps" level="0"/>

	<!-- <debug name="gui_qt5_qml" dbg_level="debug"/> -->
	<!-- <debug name="graphics_qt5" dbg_level="debug"/> -->
	<!-- <debug name="event_qt5" dbg_level="debug"/> -->
	<!--
	center= defines which map location Navit will show after first start.
	It will only be used for the first start; subsequent starts will remember the
	last position (in center.txt).
	Center coordinates format: "Long Lat" in decimal degrees (WGS 84).
	For other formats see http://wiki.navit-project.org/index.php/Coordinate_format.
	-->
	<navit center="11.5666 48.1333" zoom="256" tracking="1" orientation="-1" recent_dest="250" drag_bitmap="0" default_layout="Car">
		<!--
		The following line let you select which graphical user interface you'd like to use.
		Options include internal (optimized for touch screen devices), gtk (useful for desktop computers).
		If you don't like the internal gui, set enabled=yes for the following tag and enabled=no for the gui internal tag
		-->
		<graphics type="qt5"/>
		<!--
		In case of the internal GUI, you can even influence the size of the text and of the icons in the toolbar and the viewport.
		Here's an example for a freerunner:
		<gui type="internal" font_size="350" icon_xs="32" icon_s="96" icon_l="96"/>
		-->

		<!--
		The action that appears on map click is configurable with the attribute "on_map_click".
		To get the previous behaviour of showing the map point menu use on_map_click='menu("#Map Point")'
		-->
		<gui type="qt5_qml" enabled="yes" />
		
		<!-- for a debug log -->
		<log enabled="no" type="textfile_debug" data="debug_%Y%m%d-%i.txt" flush_size="1000" flush_time="30"/>
		<!-- osd items allow to position display and control items directly on top of the map.
		You can find a list of all the available OSDs items here:
		http://wiki.navit-project.org/index.php/OSD -->
		<osd enabled="no" type="compass"/>
		<osd enabled="no" type="navigation_next_turn"/>

		<!-- Commands include gui_internal_menu, gui_internal_fullscreen, zoom_in and zoom_out.
			Usage of negative values change the button origins. x="0" y="0" specifies the top left, x="-0" y="-0" the bottom right corner.
			It's always the top left corner of the icon, so you need to consider the icon's size when you enter the values. -->
		<osd enabled="no" type="button" x="0" y="0" command="gui.fullscreen=!gui.fullscreen" src="toggle_fullscreen.png"/>
		<osd enabled="no" type="button" x="-96" y="0" command="gui.menu(1)" src="menu.png"/>
		<osd enabled="no" type="button" x="-96" y="-96" command="zoom_in()" src="zoom_in.png"/>
		<osd enabled="no" type="button" x="0" y="-96" command="zoom_out()" src="zoom_out.png"/>

		<!-- Traffic -->
		<traffic type="null"/>

		<!-- Vehicle with GPS enabled for gpsd on unix -->
		<vehicle name="Local GPS" profilename="car" enabled="no" source="gpsd://localhost" gpsd_query="w+xj">
		<!-- Vehicle with GPS enabled for direct communication on windows. Remove the line above if you use this. -->
		<!-- <vehicle name="Local GPS" profilename="car" follow="1" enabled="yes" active="1"
				source="serial:COM4 baudrate=4800 parity=N data=8 stop=1" > -->

			<!-- Navit can write a tracklog in several formats (gpx, nmea or textfile): -->
			<log enabled="no" type="gpx" attr_types="position_time_iso8601,position_direction,position_speed,profilename,position_radius" data="track_%Y%m%d-%%i.gpx" flush_size="1000" flush_time="30"/>
		</vehicle>

		<!-- For SDL, you should add follow="1" to have the view centered on your position -->
		<!-- <vehicle name="Meins" enabled="yes" source="gpsd://localhost" color="#0000ff" follow="1"/> -->

		<vehicle name="Demo" profilename="car" enabled="yes" active="1" source="demo://"/>

		<!-- For the cumulative displacement filter to be enabled, set cdf_histsize="x" here, with x being an integer somewhere around 4 -->
		<tracking cdf_histsize="0"/>

		<vehicleprofile name="car" route_depth="4:25%,8:40000,18:10000" flags="0x4000000" flags_forward_mask="0x4040002" flags_reverse_mask="0x4040001" maxspeed_handling="0" route_mode="0" static_speed="5" static_distance="25">
			<roadprofile item_types="street_0,street_1_city,living_street,street_service,track_gravelled,track_unpaved,street_parking_lane" speed="10" route_weight="10" />
			<roadprofile item_types="street_2_city,track_paved" speed="30" route_weight="30" />
			<roadprofile item_types="street_3_city" speed="40" route_weight="40" />
			<roadprofile item_types="street_4_city" speed="50" route_weight="50" />
			<roadprofile item_types="highway_city" speed="80" route_weight="80" />
			<roadprofile item_types="street_1_land" speed="60" route_weight="60" />
			<roadprofile item_types="street_2_land" speed="65" route_weight="65" />
			<roadprofile item_types="street_3_land" speed="70" route_weight="70" />
			<roadprofile item_types="street_4_land" speed="80" route_weight="80" />
			<roadprofile item_types="street_n_lanes" speed="120" route_weight="120" />
			<roadprofile item_types="highway_land" speed="120" route_weight="120" />
			<roadprofile item_types="ramp" speed="40" route_weight="40" />
			<!--roundabout does not apply to OSMaps -->
			<roadprofile item_types="roundabout" speed="10" route_weight="10"/>
			<roadprofile item_types="ferry" speed="40" route_weight="40"/>
		</vehicleprofile>

		<vehicleprofile name="car_shortest" flags="0x4000000" flags_forward_mask="0x4000002" flags_reverse_mask="0x4000001" maxspeed_handling="0" route_mode="0" static_speed="5" static_distance="25">
			<roadprofile item_types="street_0,street_1_city,living_street,street_service,track_gravelled,track_unpaved,street_parking_lane" speed="10" route_weight="60" />
			<roadprofile item_types="street_2_city,track_paved" speed="30" route_weight="60" />
			<roadprofile item_types="street_3_city" speed="40" route_weight="60" />
			<roadprofile item_types="street_4_city" speed="50" route_weight="60" />
			<roadprofile item_types="highway_city" speed="80" route_weight="60" />
			<roadprofile item_types="street_1_land" speed="60" route_weight="60" />
			<roadprofile item_types="street_2_land" speed="65" route_weight="60" />
			<roadprofile item_types="street_3_land" speed="70" route_weight="60" />
			<roadprofile item_types="street_4_land" speed="80" route_weight="60" />
			<roadprofile item_types="street_n_lanes" speed="120" route_weight="60" />
			<roadprofile item_types="highway_land" speed="120" route_weight="60" />
			<roadprofile item_types="ramp" speed="40" route_weight="60" />
			<!--roundabout does not apply to OSMaps -->
			<roadprofile item_types="roundabout" speed="10" route_weight="60"/>
			<roadprofile item_types="ferry" speed="40" route_weight="60"/>
		</vehicleprofile>

		<vehicleprofile name="car_avoid_tolls" flags="0x4000000" flags_forward_mask="0x4000402" flags_reverse_mask="0x4000001" maxspeed_handling="0" route_mode="0" static_speed="5" static_distance="25">
			<roadprofile item_types="street_0,street_1_city,living_street,street_service,track_gravelled,track_unpaved,street_parking_lane" speed="10" route_weight="10"/>
			<roadprofile item_types="street_2_city,track_paved" speed="30" route_weight="30"/>
			<roadprofile item_types="street_3_city" speed="40" route_weight="40"/>
			<roadprofile item_types="street_4_city" speed="50" route_weight="50"/>
			<roadprofile item_types="highway_city" speed="80" route_weight="80"/>
			<roadprofile item_types="street_1_land" speed="60" route_weight="60"/>
			<roadprofile item_types="street_2_land" speed="65" route_weight="65"/>
			<roadprofile item_types="street_3_land" speed="70" route_weight="70"/>
			<roadprofile item_types="street_4_land" speed="80" route_weight="80"/>
			<roadprofile item_types="street_n_lanes" speed="120" route_weight="120"/>
			<roadprofile item_types="highway_land" speed="120" route_weight="120"/>
			<roadprofile item_types="ramp" speed="40" route_weight="40"/>
			<!--roundabout does not apply to OSMaps -->
			<roadprofile item_types="roundabout" speed="10" route_weight="10"/>
			<roadprofile item_types="ferry" speed="40" route_weight="40"/>
		</vehicleprofile>
		<vehicleprofile name="car_pedantic" route_depth="18:25%,18:40000" flags="0x4000000" flags_forward_mask="0x4000002" flags_reverse_mask="0x4000001" maxspeed_handling="0" route_mode="0" static_speed="5" static_distance="25">
			<roadprofile item_types="street_0,street_1_city,living_street,street_service,track_gravelled,track_unpaved,street_parking_lane" speed="10" route_weight="10"/>
			<roadprofile item_types="street_2_city,track_paved" speed="30" route_weight="30"/>
